openapi: 3.0.0
info:
  description: |
    This is a BelajarAPI
  version: "1.0.0"
  title: "BelajarAPI"
  contact:
    name: "adit"
    email: "wfhadit@gmail.com"
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/WFHADIT/BelajarAPI/1.0.0
  - description: local development
    url: "localhost:1000/"
  - description: production
    url: "https://domainkalian.net/{versi}"
    variables:
      versi:
        default: v1
        enum:
          - v1
          - v2
tags:
  - name: user
    description: Organize data user
  - name: activity
    description: Organize data activity
paths:
  /users:
    post:
      tags:
        - user
      summary: "register user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
            example:
              username: "wfhadit"
              email: "wfhadit@gmail.com"
              password: "wfhadit"

      responses:
        "201":
          description: "sukses menambahkan data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiDataResponse"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    get:
      tags:
        - user
      summary: "get profile user"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "sukses mendapatkan data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiDataResponse"
              example:
                code: 200
                message: "berhasil mendapatkan data"
                data:
                  id: 1
                  username: "adit99"
                  email: "wfhadit@gmail.com"
        "500":
          $ref: "#/components/responses/500"
    put:
      tags:
        - user
      security:
        - bearerAuth: []
      summary: "update profile user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: "behasil mengubah data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiDataResponse"
              example:
                code: 200
                message: "berhasil mengubah data"
                data:
                  id: 1
                  nama: "rama"
                  email: "wfhadit@gmail.com"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
  /login:
    post:
      tags:
        - user
      summary: "login user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password

      responses:
        "200":
          description: "sukses login"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiDataResponse"
              example:
                code: 200
                message: "berhasil login"
                data:
                  nama: "aditrama"
                  email: "wfhadit@gmail.com"
                  token: "wkwkwkwkwk"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
  /activity:
    post:
      tags:
        - activity
      summary: Add activity to database
      description: "Endpoint yang digunakan untuk menambahkan activity sesuai dengan hak akses pada token JWT"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiResponse"
            example:
              judul: "jogging"
              deskripsi: "lari pagi di GBK"
      responses:
        "201":
          description: "sukses menambahkan activity"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int8
                  message:
                    type: string
              example:
                code: 201
                message: "selamat data berhasil ditambahkan"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    get:
      tags:
        - activity
      summary: Get all activity data
      responses:
        "200":
          description: "sukses mendapatkan data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiDataArrayResponse"
              example:
                code: 200
                message: "berhasil mendapatkan activity"
                data:
                  - judul: "sepedahan"
                    deskripsi: "bersepedah mengelilingi jakarta"
                  - judul: "muay thai"
                    deskripsi: "bersama muay thai di kelas gym"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    put:
      tags:
        - activity
      summary: Update activity data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Activity"
      responses:
        "200":
          description: "berhasil mengubah data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiDataArrayResponse"
              example:
                code: 200
                message: "berhasil mengubah data"
                data:
                  id: 1
                  judul: "cangkul"
                  deskripsi: "mencangkul di sawah"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    delete:
      tags:
        - activity
      summary: Delete activity data
      responses:
        "200":
          description: "sukses mendapatkan data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiDataArrayResponse"
              example:
                code: 200
                message: "berhasil mendapatkan activity"
                data:
                  - judul: "sepedahan"
                    deskripsi: "bersepedah mengelilingi jakarta"
                  - judul: "muay thai"
                    deskripsi: "bersama muay thai di kelas gym"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    Activity:
      type: object
      properties:
        judul:
          type: string
        deskripsi:
          type: string
    User:
      type: object
      required:
        - username
        - email
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ApiDataResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        data:
          type: object
        message:
          type: string
    ApiDataArrayResponse:
      type: object
      properties:
        code:
          type: integer
          format: int8
        message:
          type: string
        data:
          type: array
          items:
            type: object
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"
      required: true
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/User"
      description: List of user object
      required: true
  responses:
    "400":
      description: "input data kurang tepat"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
          example:
            code: 400
            message: "terdapat kesalahan pada data input"
    "500":
      description: "server error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
